apiVersion: karpenter.k8s.aws/v1
kind: NodePool
metadata:
  name: amd64-nodepool
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/capacity-type"
          operator: In
          values: ["spot"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.small"]
        - key: "kubernetes.io/os"
          operator: In
          values: ["linux"]

      limits:
        cpu: "4000"
        memory: "16Gi"

      labels:
        environment: "arch"
        team: "amd64"

      taints:
        - key: "arch"
          value: "amd64"
          effect: "NoSchedule"

  disruption:
    consolidationPolicy: "WhenUnderutilized"
    consolidateAfter: "30s"

  deletionPolicy: "WhenEmpty"