apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: arm64-nodeclass
spec:
  amiFamily: AL2
  instanceProfile: eks-58ca8db0-a730-9cb2-01e2-a71e991ead8c
  amiSelectorTerms:
    - id: "ami-0d7c315b12e4af4ac"
  subnetSelectorTerms:
    - id: "subnet-e708b6ab"
    - id: "subnet-f3e5fe8b"
  securityGroupSelectorTerms:
    - id: "sg-0a5e648b39e3f0bfd"
