apiVersion: karpenter.k8s.aws/v1
kind: NodePool
metadata:
  name: arm64-nodepool
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/capacity-type"
          operator: In
          values: ["spot"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["m6g.small"]
        - key: "kubernetes.io/os"
          operator: In
          values: ["linux"]

      limits:
        cpu: "4000"
        memory: "16Gi"

      labels:
        environment: "arch"
        team: "arm64"

      taints:
        - key: "arch"
          value: "arm64"
          effect: "NoSchedule"

  disruption:
    consolidationPolicy: "WhenUnderutilized"
    consolidateAfter: "30s"

  deletionPolicy: "WhenEmpty"